### ISSUE TITLE
De-brief on our Project

### ISSUE THREAD

**Issue by profgeraci** [JestonBlu/Neighbor-Works#12]
Hi, guys.  I hope you had a nice break. I think it would be a good idea for us to do a de-briefing on the project so that we can figure out what we did well and what we could have done better.  I've set up a Doodle poll so that we can find a time to do another Google Hangout:  

http://doodle.com/poll/x9sxmnqefsnbqpsh
(All times here are in ET)

If you listen to tonight's Q&A session, you'll hear Prof. Ackleman make some comments about our project.  She claims that we copied the equations from somewhere else (??).     

We can talk more when we get together. 

- Anne

@JestonBlu  @nitroys @rmglazner

**Comment by JestonBlu** [comment]
That's strange. Did she say why she thought at?

**Comment by JestonBlu** [comment]
Oh, i think I understand.. looking at her comments on webassign... maybe
she thinks because we used an online latex generator that we used someone
else's equation? I generated it from a free website and saved it as an
image... maybe thats why she thinks it was copied. I think we need to
respond to her comment so she knows it wasn't copied... i also have the
latex posted in one of our discussion threads...

**Comment by profgeraci** [comment]
Yes, that's her concern.  I don't want to put words in her mouth, but I believe she thinks we got the formula from a journal article or something.  She said it looks "different" from the rest of the document and the PPT. 
No biggie.  We know it was our work.  Perhaps you could send her the LateX code, Joseph, and the website that you used to create the equation?  We haven't heard yet from Rachael, but it looks like 7:30pm ET tomorrow (that's 6:30pm CT, right?) will be a good time to meet.  
Rachael - can you do it tomorrow night?

**Comment by JestonBlu** [comment]
Since I put the equation together ill respond to her. Hopefully ill have
some feedback by tomorrow night.

**Comment by JestonBlu** [comment]
Already got a response. She said she is giving us back the credit she took
away.

**Comment by rmglazner** [comment]
Hello!

Sorry for the late response, I was in the field all morning. I am glad that we got credit back for our project! It is frustrating that she would even say something about it in the Q&A based on assumptions that she did not even talk to us about...

Anyway, I will not be available tomorrow evening, but if that is what works best for everyone else then maybe someone could write a summary about it here?

Also, I am happy to receive any feedback regarding the presentation I gave. The professor seemed surprised I was there and told me she was expecting our group to screen share even though she had written on the discussion board just a few days earlier that all local distance students were required to present in Blocker. So, if we message her far enough in advance, that may be an option for the next presentation.

**Comment by nitroys** [comment]
Thanks for taking care of that, guys. I didn't really take a close look at Dr. A's feedback, so I'm grateful you caught it. 

I'm fine with meeting tomorrow and summarizing what we talked about for Rachel.

**Comment by profgeraci** [comment]
OK, let's plan on getting together tomorrow night at 6:30pm.  I forget who did the last Google Hangout - was that you, Shannon? 

As to why she addressed it in the Q&A - I asked her specifically about what she meant by the comment - if you watch the recording you can see the interaction (pretty much the first thing in the video).   I do think it was presumptuous of her to assume that we plagiarized a journal article.  That's all I will say about that. 

I would like to discuss her other comments about our particular model because I am genuinely interested if there's a better way to model this data.  I don't think it's appropriate to treat the Neighborhood as a BLOCK - probably more appropriate as a factor of interest, but DIDN'T WE DO THAT? 

I also agree with Rachael's comment that we are really all Distance students and that we should be allowed to ScreenShare our next presentation.  We can talk about that more tomorrow.

**Comment by nitroys** [comment]
I think Rachel set up the hangout last time, but I can set it up this time. Sorry for the slow responses. Work has been a bit hectic in the last two weeks.

**Comment by JestonBlu** [comment]
Sorry, is that 630 cst?

On Mar 23, 2017 4:50 PM, "nitroys" <notifications@github.com> wrote:

I think Rachel set up the hangout last time, but I can set it up this time.
Sorry for the slow responses. Work has been a bit hectic in the last two
weeks.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/JestonBlu/Neighbor-Works/issues/12#issuecomment-288871480>,
or mute the thread

**Comment by nitroys** [comment]
It's EST, so in 10 minutes. Does that still work for you?

**Comment by nitroys** [comment]
Oh wait I'm sorry. I see Anne's post earlier, it is 6:30 cst.

**Comment by JestonBlu** [comment]
Yep, I'll be there

**Comment by profgeraci** [comment]
I'm here but I forgot my phone at work and can't login to Google with anything but akgeraci@gmail.com, so could you include me using that account?  Thanks.

**Comment by nitroys** [comment]
@rmglazner: To fill you in on the meeting from last night, we decided that we can continue this discussion on the message boards here. You'll see Anne has opened a new issue with Dr.Akleman's comments on our project. We'd like to compile some clarifying questions for her, since the comments aren't entirely clear. 

However, Joseph and I agreed that we're happy with the grade, but that maybe for the next presentation we should stick to showing only a single model to avoid confusion.

**Comment by rmglazner** [comment]
Thank you for addressing some of Dr. Akleman's comments. I saw that Anne had emailed the professor with the specific questions. Has anyone received an email response from her yet?

We should also start thinking again about how we want to assign tasks for the next part of our project. Any thoughts about that?

I am also happy with the grade, and a single model sounds good to me!

**Comment by profgeraci** [comment]
I, too, am happy with the grade that we received on our project.  Thanks, Rachael, for doing a great job presenting our material.  We have just about a month before we need to present, let's wait and see who feels like presenting - or perhaps more than one person can do it, like we saw with some of the other groups.   Personally, I think that "one voice" is probably better for the presentation - when I observed some of the other groups with more than one presenter I started making comparisons "Oh, this presenter #2 seems to have a stronger grasp on the material than presenter #1".  But that's just me.  What do you think? 

More importantly, I think, we need to decide NOW whether we want to go ahead with using this same data for the project.  As I watched all the other presentations, I started to feel a little embarrassed that our data and models weren't so interesting - low P-values, low R^2 values.  Part of this was because we had to shoehorn the data into the requirements of the project and use a CONTINUOUS predictor variable - something that was not stated at the outset of the project.    Now that we can do logistic regression, perhaps we will have more luck with predicting the RecommendCat from the other variables.  We'll have to re-code the RecommendCat into two states so that we can do a Logistic model, but that's acceptable to me.    Given what we know about the data, do you think we will have at least 4 significant predictors in the data, as required in the project?  

That said, I'm happy to switch to a different dataset if anyone has any ideas.   Thoughts?

**Comment by nitroys** [comment]
I should let you guys know now that I won't be available on the 27th to be part of the presentation. I'll be traveling, and I made that plan long before I knew there would be live components of the class...however, I can take on a larger portion of the write up/analysis, etc to make up for that. 

As far as the dataset goes, I agree with you Anne, that logistic regression will provide us a more useful analysis of the data. I would like to continue to use this dataset, because then we can avoid the learning curve of a new one. I think we'll be able to get 4 predictors, since there are a lot of explanatory variables to choose from and neighborhood ID will be kept in the model no matter what.

**Comment by profgeraci** [comment]
I also will not be available to present on the 27th.  I teach a class that ends at 3:05pm (2:05pm CT).   I will help Shannon with doing the write-up, although I think we should all help with that.  Let's try and avoid the version control problems that we had last time.  Could we all try and connect again to the following Google Drive folder:  

https://drive.google.com/drive/folders/0AHmPvYJyLr9LUk9PVA

I've invited each of you to be able to view it.  

We can continue using GitHub to track our issues and ask questions, but let's use Google to hold the documents and Data files.  

- Anne

**Comment by rmglazner** [comment]
Thank you for uploading that, Anne! I am happy to present that day, if the group wants me to. I don't want to disappoint, though. I noticed that our presentation was not one of the more highly ranked, so I understand if you all want to trade roles. Again, I am happy to talk about our data again if that works best!

**Comment by JestonBlu** [comment]
I doubt I will be available during that weekday so I think it would be
great Rachel if you dont mind presenting again. Also Im happy to continue
model building. I also agree that we should keep the same data set and I
like the logistic regression approach.
