### ISSUE TITLE
Feedback on our Models

### ISSUE THREAD

**Issue by profgeraci** [JestonBlu/Neighbor-Works#13]
(1) When I read the initial model, you wrote all as covariates.  I see the neighborhood as blocking or factor of interest not covariate. When it is a covariate, numeric values affect the results but for the factor, we look at the group effect. I can also see that you implemented as factor later.  

(2) Another problem was the ANCOVA, you directly run the equal slopes ANCOVA for the neighborhood and that may not necessarily be the case. You needed to include each factor and factor*covariate in full ancova model to start with.  

(3) I understand that sectors are your main interest but again there are other factors in the model and interactions may be significant. I can see that you covariate was age.  

(4) Also when you have many factors, the interaction affect is also an interest and you did not investigate.

**Comment by profgeraci** [comment]
Anne's questions:
(1)  Why does she think that we used "all as covariates"?  The neighborhood ID is a factor of interest, but it is defined in JMP as nominal.  Is there something in our JMP output that makes her think it's a covariate.  This confused me.

(2)  I have no idea what she means by "run the equal slope ANCOVA".  Can someone explain what that means. 

(3) What other factors should we have used?

(4) So, were we to have investigated the interactions between Age and things like PoliceRatingCat?

**Comment by nitroys** [comment]
My questions/thoughts:
For 1), I think it might be a word choice thing. We specified an ANCOVA model, so only age was a covariate in the sense that it was a continuous variable that we thought might have an effect, but it was not of primary interest. In the report, we used the word covariates in the "explanatory variables" sense of the word, hence her confusion there, perhaps. 

I'm not sure what she means by 2) either, unless she's just suggesting we should have switched the order in which we presented our models so that the one with interactions (unequal slopes model) was first? But I'd like clarification on this as well.

3) Does she mean we should have tested interactions of age (the covariate) with all of the factors in our model? (similar to your question 4 Anne)

4) Here I think she might mean the interaction between the factors themselves, so like PoliceRatingCat*TrashRatingCat, etc.
