### ISSUE TITLE
Pulling things together

### ISSUE THREAD

**Issue by profgeraci** [JestonBlu/Neighbor-Works#8]
Hi, gang.  I've posted an initial draft of what I propose as our Project Document under "Code".  Please feel free to pull down a copy, turn on track changes and comment on anything you like.  I'm kind of waiting now for Joseph to figure out exactly what type of model we're going to use and which variables  we need.  

Once we have reached consensus on that, I can modify the document to reflect this - or anyone else can if you get to it first.  

I'll be in and out this weekend, but ready to pull this together next week.  

- Anne

**Comment by JestonBlu** [comment]
Thanks Anne, Ill start posting some results tomorrow morning.

**Comment by rmglazner** [comment]
Thank you, Anne! Once the results are uploaded, I will start putting together a Powerpoint. I will upload the first draft of the presentation Monday afternoon. Shannon, would you be able to upload a draft of the discussion/conclusion Monday as well? I can add any details you have after that.

Lastly, can we have a video meeting Wednesday (March 1) late afternoon or evening? This way I can give you all the practice talk, and I can use your feedback to give a better presentation the next day.

**Comment by rmglazner** [comment]
My page says that Shannon is not a participant of this page, is there any way I can change that so she sees these messages?

**Comment by rmglazner** [comment]
Sorry for so many comments, but I edited the first draft of the report, and I cannot understand how to upload it for other members to edit as well. I created a post called "RG Edits" but I do not know how to upload the word document to it. Can someone help me understand how to do this?

**Comment by JestonBlu** [comment]
I think you just need to send her a tag once and she will be on the thread @nitroys . I think she only shows up as a participant if she replies to a comment.

**Comment by nitroys** [comment]
Hi all,

I can certainly have a draft by the end of the day Monday. I might be available to meet Wednesday depending on the time, but if not, I trust what you're able to put together!

**Comment by nitroys** [comment]
Rachel, I've just uploaded my version of the report Anne started. It's under Code > Project1 Writeup. I wasn't able to find the document you uploaded, so I guess you're still having trouble with that. I went to the Code tab and clicked on "upload files" in the top right and dragged my version of the file with the same name into the box. Hope that helps!

**Comment by JestonBlu** [comment]
You should also be able to just drag and drop files on any folder location.

**Comment by rmglazner** [comment]
Thank you both for your help, I was able to get the document uploaded! I read through the most recent version of the report that Shannon added, and I wrote some comments and uploaded that document with the name Project1 Writeup EDITS.

Although I mention these in the documents, here are some major thoughts so far:
1) I think the report has a 5 page limit, and we currently have a 7 page report, so we will need to trim down some of our project. I think that this can mostly happen with the large table currently in the report.
2) I think at least one graph would help visualize the data.
3) I think in the introduction when we talk about our models, we should write in the present tense, not future tense.

**Comment by rmglazner** [comment]
Overall, the report looks good though! As I have mentioned, I will upload a draft of the Powerpoint tomorrow afternoon for you all to look at and suggest any changes.

Is there a time Wednesday afternoon that works for a video conference to practice the presentation and provide any further suggestions for improvement? I am available any time to meet. Can you all please list the time ranges Wednesday you are available to possibly meet? It would be great if all 3 of you had a shared free time, but I understand if only 2 of you are available at the same time that day!

Please let me know, thank you!

**Comment by profgeraci** [comment]
Hi, Rachael.  I am available all day Wednesday except for about 12:30pm to 2:30pm.  Shall we do a Google Hangout?

**Comment by nitroys** [comment]
I should be available most of the day Wednesday too, before 6pm.

**Comment by JestonBlu** [comment]
I probably wont be available till 5PM CST on Wednesday. If i cant make it
Ill make myself available that night to answer any follow up questions if
there are any.

**Comment by profgeraci** [comment]
So, 5pm CST is 6pm EST, right?  I think we need to have Joseph in on the call, since he has done the modeling.  Shannon - is there any way you can do it at 6pm EST (or 5pm CST)?

**Comment by nitroys** [comment]
Sure, I can meet at 6 EST for about half an hour, but I'll have to leave by 6:30.

**Comment by rmglazner** [comment]
Okay, so it sounds like we will meet at 5:00 CST this Wednesday. Google Hangout works for me if that is okay with everyone else!

**Comment by profgeraci** [comment]
Are you going to set this up, Racheal?  You'll have to tell us how to connect to Google Hangout.  I've never done that before.

**Comment by JestonBlu** [comment]
Same with me, not sure where to go tonight

**Comment by rmglazner** [comment]
My apologies for the delay in responding, I was driving from Galveston to College Station this afternoon so that I can present in Blocker tomorrow. It would have been nice if the professor stated she wanted local distance students to present in Blocker more than 3 days before the project haha.

I have added all three of you to a Google Hangouts conversation. I will call the group in about 45 minutes. In order to receive the call, you all should be logged into the email addresses you used when we initially started discussing the project before starting GitHub. Once you are logged in there, you will be notified that you are receiving a call. All you should have to do after that is answer, and the video call will begin.

I am making a few final changes to the presentation and I will have it uploaded before I call so that we can go through it as a group!

Talk to you all soon!

**Comment by profgeraci** [comment]
So, we are going to use GitHub?  I've mostly been using the browser version and didn't know it could do video calls.   .... or do you mean Google somewhere?    I just went to Google Hangouts and that looks more like where we need to logged in.  I have a couple of different gmail accounts.  I'm currently logged in with this one:  ageraci@tamu.edu

**Comment by JestonBlu** [comment]
i think we are using google, im logged in now as well under jblubau1@tamu.edu

**Comment by JestonBlu** [comment]
on my calls tab it says calls are unavailable, im not sure if that is significant though

**Comment by nitroys** [comment]
I'm logged into the hangouts app under L03982502@tamu.edu as well.

**Comment by profgeraci** [comment]
Shannon - Rachael just invited you to the call.  Do you see that?

**Comment by nitroys** [comment]
I do not.

**Comment by nitroys** [comment]
Okay, I've got a new version of the report uploaded (nearfinal writeupSRN.doc) and put my SAS code for hw5 in Code as well.

**Comment by JestonBlu** [comment]
I also added and updated latex model gif to the main folder

**Comment by nitroys** [comment]
I have a final version of the report uploaded to Code. Take a look and let me know what you guys think. I'll submit it as soon as we're all okay with it.

**Comment by rmglazner** [comment]
I accidentally posted this in the wrong discussion area, so I am posting it again here (sorry about that!):

Thank you for making those changes! Overall it is looking good, but the title still needs to be changed so that it matches the title of the PowerPoint I uploaded. Can you please change the title to "Identifying Factors Associated with Residence in Subsectors of a Rochester Neighborhood"?

Other than that, the only other comment I have is if you can please add a sentence or to about why we chose to use log(years) rather than just years.

Some of my comments from previous drafts still appear on the final writeup, so as long as you delete those before submission it should be okay!

Thank you again!

**Comment by rmglazner** [comment]
Also, is there any way we can change the font size from 10 to 12?

**Comment by nitroys** [comment]
Whoops, good catch on the title. I do have a sentence about logging years in the Methods section.

If we make the font any bigger it goes over 5 pages....

**Comment by rmglazner** [comment]
Thank you! I looked back at the methods and just saw the sentence, sorry I missed it before!

I don't see any requirement that the font has to be a certain size, so if we have to keep it at size 10 then I am sure it is okay!

**Comment by rmglazner** [comment]
I also deleted the old PowerPoint and uploaded a new one to Code. The most recent version is the one I plan to present today.

**Comment by rmglazner** [comment]
IMPORTANT: Do not submit the report yet! Please watch the presentation video, she expects there to be certain analysis in the report that is not written there yet!

**Comment by JestonBlu** [comment]
The video hasn't been posted yet. How did the presentation go?

**Comment by rmglazner** [comment]
Okay, my guess is that she will post it on the website she gave the link for at 6:30, since that is when the regular lectures are uploaded.

Overall, the presentation went really well I think. Our analyses and interpretation were correct, and I could see her frequently nodding her head as I explained out justification for our model, and explained our different variables.

During the questions section I personally thought that I could have done better (it is difficult for me to have answers immediately compared to prepared statements), but I tried my best and it was not too bad!

**Comment by JestonBlu** [comment]
Excellent, great to hear!

**Comment by nitroys** [comment]
Yay I'm glad it went well!! I'll take a look at the video tomorrow and make sure I get the report changed and submitted before 12:45 CST :)

**Comment by profgeraci** [comment]
Well, if the video isn't going to be published until tomorrow morning, I think we need to ask for more time to prepare the report.  I don't know what additional analyses she asked for (darn, don't you hate those "emerging" requirements), but it isn't reasonable to have to post something within such a small time window.  

Racheal:   What did she ask for?

**Comment by JestonBlu** [comment]
I wont be able to watch the video before the time the paper is due, but if you can let me know what needs to change I can load JMP on my work computer in the morning and make any model adjustments that we need to.  If changes are needed that is.

**Comment by rmglazner** [comment]
There were a few comments, and from what I can remember she mentioned that the Parameters Estimates table for our ANCOVA tests different values compared to the lowest value, and that we should have analysis that also compared them all to each other I think (with slopes for each?). I was really nervous so I hope I am not relaying the information incorrectly :( Does that make sense to any of you, or at least give an idea of what she was suggesting? Joseph, is there a specific type of code that incorporates the low, medium, and high values without comparing them to just the low value? I am sorry for the delay of my response, I wrongly assumed she would upload the presentations in the same time she uploads normal lectures!

Thank you Shannon, for helping out with these last-minute changes, I really appreciate it!

**Comment by rmglazner** [comment]
Everything we have right now is good, I think she was just looking for a little extra analysis in addition to the parameter estimates tables we provided! She asked if it was in the report in a way that made it seem like she was expecting it, so I said just said yes (I am sure you will all eventually see hat I am talking about when she uploads the videos). I didn't want to say anything to hurt her impression of our group, sorry if that causes any confusion!

**Comment by nitroys** [comment]
Ohh so she's looking for some interaction terms as well. So maybe neighborhoodID interacted with trashrating, policerating and ownrent? Then we can look at the difference in slopes for each subsector.

**Comment by nitroys** [comment]
Is there a reason why the other groups' videos are posted but not ours...?

**Comment by nitroys** [comment]
Okay, looking at Dr. Akleman's discussion post, we won't be able to see the video before the report is posted. But, I trust what you're saying, Rachel, because I think it makes sense to try some interactions with our variable of interest to test whether they have different slopes. Joseph, whenever you get a chance to do that, I can finish up the report at any point. I'm working from home today, so no one can interrupt me :)

**Comment by profgeraci** [comment]
(grumble grumble grumble .... wipes eyes and shakes it off).  
OK, Let's do this.  I'm working at home this morning until 10:30, then I won't be available until after 3pm.    NOTE:  Shannon - last night I pulled down the document and tried changing the font to Times New Roman 12pt (from Garamond 10), but it expanded beyond the 5 page limit.   We should probably just stay at 10pt - so you can either go back to the previous version (that you uploaded yesterday morning) or change the font.  Let me know if I can help with anything.

**Comment by JestonBlu** [comment]
I will add an interaction term and let you know.

**Comment by rmglazner** [comment]
Is there a way that each value (low medium high) can be interpreted independently as well? I think she was saying that medium and high values were being compared to low values within each factor, but that they should be looked at as independent values as well (again, for me it was not 100% clear what point she was trying to make)? I am not sure if she was looking for interaction or individual value interpretation (if that makes sense), but both would probably help if possible.

**Comment by rmglazner** [comment]
I think as long as we expand our parameters estimates table beyond what was in the presentation, we should be okay. Everything we did seemed to be correct, I think she just wanted a little more for that part.

**Comment by JestonBlu** [comment]
Okay, the only thing I think we could do is switch the categorical variables to ordinal which I can do quickly, but it might cause a few more edits in the written report, because instead of comparing Police Rating High and Medium to Low, it would be compairing Medium to Low and High to Medium.  This doesnt affect the overall fit of the model, but it may make it easier to understand what is going on. 

In terms of assessing each level independently... the only way I think we could take a stab at that would be if we broke the ratings out into dummy variables, but I dont think we have time for that... still one has level has to be in the intercept, so maybe I dont exactly understand what she is asking for...

I have created 2 reports new reports with an interaction between NeighborhoodID and Age... i tried all of the interactions, but I was seeing a lot of warnings about estimate bias and loss in DF and all of the LS Means values were not estimable so something was going wrong there. Age and NeighborhoodID were not significant but it does show that we tested for it.

Here is a sample output from just adding the interaction..

![image](https://cloud.githubusercontent.com/assets/3339909/23555924/4c01fe76-fff0-11e6-94e8-8cc59c22922e.png)

And here is a sample from the output where the predictors have been changed to ordinal... notice that that some of the signs have changed since the comparisons are different.

![image](https://cloud.githubusercontent.com/assets/3339909/23556024/9f8614ce-fff0-11e6-96d6-aaf4e13bf2c0.png)

Ive pushed both versions as PDFs in the Reports folder. Let me know what you think. I vote we go with the ordinal version unless its going to be too many last minute changes

**Comment by JestonBlu** [comment]
Also, the contrasts in the report should be updated to the new contrast table, since we only have 4 neighborhood IDs we can only do 3 contrasts, Initially I did 4 separate contrasts in SAS, but that was inappropriate. Still they were all not significant.

**Comment by rmglazner** [comment]
Thank you for the extra analysis, Joseph! Just so I understand the table correctly, what does a positive coefficient for PoliceRatingCat[medium-high] indicate? It is significant and positive, so does that mean as police rating moves from high to medium, years of residence increases?

I think that this extra information looks good, but I am worried that if we replaced what we have with ordinal analysis she may not like that our presentation and report are different. The 5 page limit makes this difficult, but could we add these tables in addition to what we already have to show that we approached the data in multiple ways? I think an extra sentence similar to what you said about the comparisons and then including these two tables would help a lot. If the results are similar, we can say that our conclusions are more greatly supported by multiple approaches maybe?

**Comment by rmglazner** [comment]
I think if we made the map images smaller we would have room for the extra tables.

**Comment by nitroys** [comment]
I'll give it a shot at fitting it all in. I like the ordinal analysis too, though I'm surprised the interactions were giving you trouble. But I guess it depends on how the variables are structured.

**Comment by JestonBlu** [comment]
Yeah, im not sure... not a lot of time to dig into it though... so that way I would interpret the PoliceRating of High compared to Medium is that on average people who rated Police as high have lived in their residence 30% longer than those who rated Police as medium. And then of course there is no significant difference between those who rate police medium vs low.

**Comment by nitroys** [comment]
Sorry, where is the new contrast table?

**Comment by JestonBlu** [comment]
It looks a little different in the JMP output, its kind of buried, but here it is

![image](https://cloud.githubusercontent.com/assets/3339909/23557696/81e1ced0-fff6-11e6-822a-2e28c1d4cb3b.png)

**Comment by nitroys** [comment]
Ah okay. That's what I thought, but wanted to make sure. Thanks! Almost done making changes, will upload it soon for a final look through from you all.

**Comment by nitroys** [comment]
Okay, it's called postpresentationwriteup and can be found in Code.

**Comment by JestonBlu** [comment]
I think it looks good, I dont have any edits

**Comment by rmglazner** [comment]
I agree!

**Comment by nitroys** [comment]
Great! I'll give Anne some time to look over it before I submit. Joseph, are your final dataset and JMP code versions uploaded? I can submit those when I submit the report, I just want to make sure I have the right ones.

**Comment by rmglazner** [comment]
If the interaction is insignificant, should we have the ordinal data be presented without the interaction term? Otherwise we are comparing a model with an interaction to a model without an interaction.

**Comment by rmglazner** [comment]
I just thought of that. I don't know if it is that important, but I just wanted to check!

**Comment by nitroys** [comment]
I think it's fine the way it is, given the time constraint.

**Comment by rmglazner** [comment]
Okay!

**Comment by profgeraci** [comment]
Hi, guys. Unfortunately I will not be able to look at it before it's due. I'm going through thyroid cancer and have an appt with my doctor today. Timing! Please go ahead without me. 

- Anne

**Comment by JestonBlu** [comment]
You can just submit the `ReducedData.jmp ` data set. It has the models saved as scripts inside the data table and they all have the same titles as the report names I generated.  The last thing I ran was with the data changed to ordinal so if she runs `ANCOVA--log(Years) Model 3 (Best with interaction)` she is going to get the ordinal version.

**Comment by nitroys** [comment]
Oh Anne, I'm so sorry to hear that. No worries, I hope your doctor's appointment goes well.

Thanks Joseph! I'll go ahead and submit all this stuff now.

**Comment by JestonBlu** [comment]
Sorry to hear that Anne. I think the report is high quality. Im comfortable submitting.

**Comment by rmglazner** [comment]
Anne, I am really sorry to hear that. I agree what we have is good, thank you for submitting it for us.

**Comment by profgeraci** [comment]
Thanks for your thoughts all.  I appreciate all your efforts to get the project submitted before the deadline.  The report looks really good (IMHO) and reflects all of your hard work.   I'm impressed that we were able to say what we wanted to say in 5 pages!   If we all lived closer I would buy everyone a beer!
