### ISSUE TITLE
Best Model

### ISSUE THREAD

**Issue by profgeraci** [JestonBlu/Neighbor-Works#9]
Joseph:  Thanks for all this great work.  I think this is really coming together.  I have a few questions about the ANCOVA - log(Years) Model 2 (Best Model), which I presume is the one you want to put forward for our project. 

1.  How is the Years_adj variable computed?    Can you elaborate a bit on that? 

2.  I agree with the comment that we should present the model WITH the Neighborhood ID (since that's what was specifically asked), but then show it WITHOUT the Neighborhood to see if anything changes. 

.... So, it looks like our best model is:

log(Years_Adj) ~ Age + OwnRent + PoliceRatingCat + FeelSafeDayCat + TrashRathingCat + Neighborhood ID

@nitroys @rmglazner @JestonBlu

**Comment by JestonBlu** [comment]
Correct, i think log(Years) Model 2 is the best one so far. 

1. Years adjust is simply Years + 1, because some residents responded with 0. This is just a trick to so that we can still use a log transformation. Since every observation received this +1 there should be no adverse impact on the analysis. In fact, when presenting to NW I would maybe not mention the adjustment.

2. So everyone initially indicated the interest in seeing the correlation for Age and Years. I didn't do a correlation directly, but I did do a simple regression model of Years ~ Age, and the r2 ended up being around .30. In the best model with additional predictors the r2 is around .43.  So it appears that Age alone makes up about 70% of the total explained variation in the number of years lived in the residence.

To me this intuitively makes sense. I know the initial plan was to try and use to Neighborhood ID more directly, but since we have some constraints on what we can present in class, we are really looking for a model to explain the number of years someone has lived in their home. It makes sense to me that the older you are the longer you have probably lived where you are, hence Age is by far the best predictor in the model so far.

**Comment by nitroys** [comment]
I've uploaded a new version of the report (I renamed it, so it looks like it appears as a separate item under Code) where I addressed some of everyone's comments and added output for the model without neighborhood ID. 

I think the biggest thing left to do is to reformat the table with the variables in it to take up less space.

**Comment by rmglazner** [comment]
Thank you all for your contributions to the report, this is very helpful for me to put the presentation together! I am looking at the most recently updated draft, and the changes made are great. One suggestion I have is to describe the results before presenting the figures, and then cite each figure within the description.

For example: Neighborhood ID is not significant, but the years of residence is lower for sector 1 relative to sector 4, but higher for sectors 2 and 3 relative to sector 4 (Figure 3).

This way the reader understands what the major findings are, and then they can reference the table and graph after that.

Thank you all again!

**Comment by JestonBlu** [comment]
We could add a contrast to see if Neighborhood (2,3,4) is different that
Neighborhood 1.

**Comment by rmglazner** [comment]
I agree that a contrast could be nice.
